branch-defaults:
  default:
    environment: janus-env
    group_suffix: null
  master:
    environment: janus-env
environment-defaults:
  janus-env:
    branch: null
    repository: null
global:
  application_name: janus
  branch: null
  default_ec2_keyname: Henry's Laptop Key Pair
  default_platform: Python 3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
