# Generated by Django 2.1.7 on 2019-03-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    atomic = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the choice', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the decision you need help making', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='decision',
            field=models.ManyToManyField(help_text='Select a decision for this choice', to='dartboard.Decision'),
        ),
    ]
