# Generated by Django 2.1.7 on 2019-03-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('dartboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Choice',
        ),
    ]
