# Generated by Django 2.1.7 on 2019-03-27 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dartboard', '0007_auto_20190327_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='author',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='choice',
            name='decision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dartboard.Decision'),
        ),
    ]
